# Generated by Django 4.2.1 on 2023-06-12 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('image', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('link', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
