# Generated by Django 4.2.1 on 2023-06-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='bought',
            new_name='bought_by',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='liked',
            new_name='liked_by',
        ),
    ]
