# Generated by Django 4.2.1 on 2023-06-27 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_bought_event_bought_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
