# Generated by Django 4.2.1 on 2023-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image_alter_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventId',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
