# Generated by Django 4.2.1 on 2023-06-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('memoirs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoir',
            name='event',
        ),
        migrations.AddField(
            model_name='memoir',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memoir', to='events.event'),
            preserve_default=False,
        ),
    ]
