# Generated by Django 4.2.1 on 2023-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bought_events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought_event',
            name='user',
        ),
    ]
